# Generated by Django 4.1.6 on 2023-02-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0002_alter_matiere_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Niveaux',
            new_name='Categories',
        ),
    ]
