# Generated by Django 4.1.6 on 2023-02-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0003_rename_niveaux_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='niveau',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='matiere',
            old_name='niveau',
            new_name='categorie',
        ),
        migrations.AddField(
            model_name='lesson',
            name='langue',
            field=models.CharField(choices=[('toutes_langues', 'Toutes les langues'), ('anglais', 'Anglais'), ('francais', 'Français')], default='toutes_langues', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='niveaucompetence',
            field=models.CharField(choices=[('debutant', 'Debutant'), ('intermediaire', 'Intermediaire'), ('avance', 'Avance')], default='debutant', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='payant',
            field=models.BooleanField(default=False),
        ),
    ]
