# Generated by Django 4.1.6 on 2023-08-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0005_epreuve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epreuve',
            name='miniature',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
